<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>_2___my_finance_web_dotnet_service</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\3-) my-finance-web-dotnet-domain\3-) my-finance-web-dotnet-domain.csproj"/>
    <ProjectReference Include="..\4-) my-finance-web-dotnet-infra\4-) my-finance-web-dotnet-infra.csproj"/>
  </ItemGroup>
</Project>
