<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>myfinance_web_dotnet_infra</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\3-) my-finance-web-dotnet-domain\3-) my-finance-web-dotnet-domain.csproj"/>
  </ItemGroup>
</Project>
